### PR TITLE
Use `rcodetools.gemspec` and `gem push`

### PR DESCRIPTION
**Pull request by aycabta**
I succeeded to release to local RubyGems.org by `rake release` with [`--host` option for `gem push`](http://guides.rubygems.org/command-reference/#gem-push).

### CODE REVIEW

**Comment by mattn** [comment]
Great!

**Comment by mattn** [comment]
BTW, how to run tests?

**Comment by aycabta** [comment]
`rake test`

**Comment by aycabta** [comment]
After https://github.com/rcodetools/rcodetools/issues/18 fixed, `bundle exec rake test` is better of course.

**Comment by mattn** [comment]
Thanks.

**Pull request merged**
